name: Check

on:
  schedule:
    - cron: 0 16 * * *
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: 检出当前仓库代码
        uses: actions/checkout@v6

      - name: 计算所有镜像的综合哈希
        id: getHash
        shell: bash
        env:
          DEBIAN_FRONTEND: noninteractive
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
          LIST_FILE: containers.list
          MANIFEST_FILE: manifests.raw
        run: |
          if ! command -v skopeo &>/dev/null; then
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install skopeo
          fi

          skopeo login -u "${DOCKER_USER}" -p "${DOCKER_PASS}" docker.io

          {
            while read -r source_image || [[ -n "${source_image}" ]]; do
              source_image="${source_image#"${source_image%%[![:space:]]*}"}"
              source_image="${source_image%"${source_image##*[![:space:]]}"}"
              [[ -z "${source_image}" || "${source_image}" == "#"* ]] && continue

              skopeo inspect --raw --retry-times 3 "docker://${source_image}" 2>/dev/null || echo "${source_image}-failed"
            done <"${LIST_FILE}"
          } >"${MANIFEST_FILE}"

          hash_raw=$(sha256sum "${MANIFEST_FILE}")
          images_hash="${hash_raw%% *}"

          echo "imagesHash=${images_hash}" >>"${GITHUB_OUTPUT}"

          unset source_image hash_raw images_hash

      - name: 对比镜像哈希（缓存校验）
        id: cacheHash
        uses: actions/cache@v5
        with:
          path: .imagesHash
          key: imagesHash_${{ steps.getHash.outputs.imagesHash }}

      - name: 保存新的镜像哈希到文件
        if: steps.cacheHash.outputs.cache-hit != 'true'
        run: |
          echo "${{ steps.getHash.outputs.imagesHash }}" | tee .imagesHash

      - name: 触发同步工作流
        if: steps.cacheHash.outputs.cache-hit != 'true'
        run: |
          gh workflow run Sync
